export const SCROLL_DEMO_PAGE_ROUTE = "scroll" as const;
export const ROTATE_DEMO_PAGE_ROUTE = "rotate" as const;
export const MAIN_PAGE_ROUTE = "/" as const;
export const DEMO_PAGE_ROUTE = "/demo" as const;
export const AUTH_DEMO_PAGE_ROUTE = "auth" as const;
export const AUTH_CALLBACK_DEMO_PAGE_ROUTE = "auth/callback" as const;
export const SCROLL_TEXT_DEMO_PAGE_ROUTE = "scroll-text" as const;
export const MARQUEE_DEMO_PAGE_ROUTE = "marquee" as const;
export const BUTTON_DEMO_PAGE_ROUTE = "button" as const;
export const MODAL_DEMO_PAGE_ROUTE = "modal" as const;
export const N_QUIZ_EVENT_PAGE_ROUTE = "/quiz-event" as const;
export const NEW_CAR_PAGE_ROUTE = "/new-car" as const;
export const N_PARTS_PICK_PAGE_ROUTE = "/parts-pick" as const;
export const PICK_EVENT_PAGE_ROUTE = "/pick-event" as const;
export const PARTS_COLLECTION_PAGE_ROUTE = "/parts-collection" as const;
export const SHARE_PAGE_ROUTE = "/share/:linkKey" as const;
export const N_QUIZ_EVENT_PAGE_WINNER_APLLY_PAGE_ROUTE =
  "/quiz-event-apply" as const;
export const LOTTER_APPLY_FINISH_PAGE_ROUTE = "/lottery/apply-finish" as const;
