name: diff-check
on:
  workflow_call:
    inputs:
      relative:
        required: false
        default: './'
        type: string
      is_merge:
        required: true
        type: boolean
jobs:
  diff-check:
    runs-on: ubuntu-latest
    steps:
      - name: Set HEAD variable
        id: set-head
        run: echo "::set-output name=head::main"
        if: inputs.is_merge

      - name: Set main~1 variable
        id: set-main
        run: echo "::set-output name=head::main~1"
        if: ${{ !inputs.is_merge }}
        
      - name: Make Last Hash
        id: last
        run: |
          LAST_HASH=$(git rev-parse ${{ steps.set-head.outputs.head || steps.set-main.outputs.head }}:${{ inputs.relative }})
          echo "::set-output name=hash::$LAST_HASH"

      - name: Make Current Hash
        id: current
        run: |
          CURRENT_HASH=$(git rev-parse HEAD:${{ inputs.relative }})
          echo "::set-output name=hash::$CURRENT_HASH"

      - name: Set Diff
        id: diff-check
        run: |
          if [ "${{ steps.last.outputs.hash }}" != "${{ steps.current.outputs.hash }}" ]; then
            echo "::set-output name=diff::true"
          else
            echo "::set-output name=diff::false"
          fi
