name: Deploy Service to Firebase Hosting on PR
on: pull_request
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - uses: actions/checkout@v3
      
      - name: Run diff-check
        id: diff-check
        uses: ./.github/workflows/diff-check.yml
        with:
          relative: ./packages/service
          is_merge: false
      - name: package-folder
        run: cd ./packages/service
      - name: Create .env file
        if: ${{ steps.diff-check.outputs.diff }}
        run: |
          jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' <<< "$SECRETS_CONTEXT" > .env
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
          
      - name: Install Dependencies and Build
        if: ${{ steps.diff-check.outputs.diff }}
        run: |
          npm install -g pnpm && pnpm install && pnpm build
          
      - name: Deploy to Firebase Hosting
        if: ${{ steps.diff-check.outputs.diff }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WATERMELON_CLAP }}
          projectId: watermelon-clap
